/**
 * Publications éditoriales du portail (billets). Rendues par <PublicationArticle>
 * à partir de données structurées — texte échappé par React, aucune injection HTML.
 * Bilingue FR/EN (le contenu officiel de loi n'est jamais traduit ; ces billets,
 * eux, sont éditoriaux et fournis par l'auteur dans les deux langues).
 */
import type { LegalBlock } from './legal'

export interface PublicationData {
  slug: string
  date: string
  dateEn: string
  author: string
  kicker: string
  kickerEn: string
  titleFr: string
  titleEn: string
  summaryFr: string
  summaryEn: string
  bodyFr: LegalBlock[]
  bodyEn: LegalBlock[]
  /** Références (notes de bas de page) — version anglaise annotée. */
  refsEn?: string[]
}

const EGOUVERNANCE: PublicationData = {
  slug: 'egouvernance',
  date: '14 juin 2026',
  dateEn: 'June 14, 2026',
  author: 'Me Christelle Vaval',
  kicker: 'Publication · Droit du numérique',
  kickerEn: 'Publication · Digital law',
  titleFr: "eGouvernance en Haïti : sécurisation et transparence de l'administration publique",
  titleEn: 'eGovernance in Haiti: securing and ensuring transparency in public administration',
  summaryFr:
    "La digitalisation des services publics est une avancée pour Haïti — à condition que les plateformes respectent la transparence, la protection des données et la sécurité que la loi impose. Analyse des obligations issues du Décret de 2016 et de l'Arrêté de 2018 : politique de confidentialité, durée de conservation, localisation des données et CLOUD Act, bilinguisme, DNSSEC et droits des administrés.",
  summaryEn:
    'The digitalization of public services is a step forward for Haiti — provided platforms uphold the transparency, data protection and security the law requires. An analysis of the obligations under the 2016 Decree and the 2018 Order: privacy policy, retention, data localization and the CLOUD Act, bilingualism, DNSSEC and citizens’ rights.',
  bodyFr: [
    { t: 'p', s: "La digitalisation des services publics constitue une avancée positive pour Haïti. Le Décret du 6 janvier 2016, reconnaissant le droit de tout administré à s'adresser à l'Administration Publique par des moyens électroniques, pose les bases d'une administration électronique moderne et respectueuse des droits des citoyens. Il vise à réduire les barrières d'accès aux services publics, à simplifier les démarches administratives et à améliorer la transparence." },
    { t: 'p', s: "Qui dit modernisation, dit également de nouveaux défis. Le Décret de 2016 établit des normes pour garantir la sécurité des systèmes électroniques, la confidentialité des données personnelles et la protection de la vie privée, tout en encourageant la coopération entre les entités administratives pour assurer l'interopérabilité des systèmes et des applications. Il met aussi l'accent sur la réduction de la fracture numérique et la préservation du bilinguisme (créole et français) dans les services électroniques." },
    { t: 'p', s: "C'est dans cette optique que plusieurs organes de l'État ont commencé à se moderniser pour mieux servir la population. Mais la confiance dans ces services suppose le respect des droits des utilisateurs. L'utilité de ces plateformes implique que les exigences de transparence et de protection déjà prévues par la législation en vigueur soient effectivement mises en œuvre lors de la conception de ces outils." },

    { t: 'h2', id: 'donnees', s: 'La protection des données personnelles : un droit reconnu' },
    { t: 'p', s: "L'Arrêté du 30 avril 2018 sur la protection des données à caractère personnel reconnaît le droit des citoyens à la protection de leurs informations. Les principes qu'il consacre sont reconnus internationalement : finalité, proportionnalité, durée limitée, confidentialité, sécurité, droit d'accès et droit de rectification. Ces principes sont alignés avec les standards internationaux, notamment le Règlement Général sur la Protection des Données (RGPD) de l'Union européenne et les Lignes directrices de l'OCDE." },
    { t: 'p', s: "Les données collectées par les plateformes gouvernementales comptent parmi les plus sensibles qui soient : le Numéro d'Identification National Unique (NINU), les numéros de passeport, la date de naissance, les coordonnées de cartes de crédit, l'adresse personnelle, le numéro de téléphone. Ce sont des données intrinsèquement liées à l'identité de chaque individu. Si des personnes non autorisées y accèdent, elles pourraient servir à l'usurpation d'identité, à la fraude documentaire, ou à la surveillance non autorisée." },
    { t: 'p', s: "En effet, un cyberattaquant pourrait capturer ces numéros d'identification, les croiser avec les adresses et les numéros de téléphone pour constituer des profils complets. Le Décret de 2016 a prévu ce type de risque en son article 4 f) en exigeant un niveau de sécurité au moins égal à celui offert par les moyens non électroniques." },

    { t: 'h2', id: 'transparence', s: 'Transparence, politique de confidentialité et durée de conservation' },
    { t: 'p', s: "Dans le cadre de la mise en confiance des utilisateurs, les politiques de confidentialité jouent un rôle essentiel. Elles informent le citoyen de la nature des données collectées, de leur finalité, de leur durée de conservation et des personnes autorisées à y accéder. Or, sur plusieurs plateformes gouvernementales existantes, ces politiques sont soit absentes, soit non prévues, ou inaccessibles. On observe des cas où il n'y a pas d'espace prévu à cet effet sur le site en question, et d'autres où les liens en pied de page redirigent vers des pages entièrement vides." },
    { t: 'p', s: "Le principe de proportionnalité, autrement dit de minimisation des données, prévu par l'Arrêté de 2018 précise qu'il « n'est requis des administrés que les données strictement nécessaires à la finalité pour laquelle elles sont demandées ». Sans politique de confidentialité publiée, il est impossible pour l'administré de vérifier si ce principe est respecté." },
    { t: 'p', s: "L'absence de politique de confidentialité entraîne également une autre lacune : il est difficile d'identifier, sur les plateformes examinées, la durée pendant laquelle les données soumises par les administrés seront conservées. L'Arrêté de 2018 exige pourtant, en son article 3, alinéa 3, que les données soient « conservées pour une durée établie en fonction de la finalité du fichier en question ». Ce principe de durée limitée signifie que les données personnelles ne doivent pas être conservées indéfiniment et doivent être supprimées ou anonymisées dès lors qu'elles ne sont plus nécessaires à la finalité pour laquelle elles ont été collectées." },
    { t: 'p', s: "Concrètement, un voyageur qui remplit un formulaire d'entrée ou de sortie du territoire ne sait pas si ses données personnelles (numéro de passeport, adresse personnelle, numéro de téléphone, itinéraire de voyage) resteront dans le système un mois, un an, dix ans, ou indéfiniment. Un entrepreneur qui enregistre son entreprise en ligne ignore combien de temps ses informations personnelles et ses données de paiement seront conservées au-delà du traitement de sa demande." },
    { t: 'p', s: "Cette absence d'information crée des risques comme celui d'empêcher l'administré de donner un consentement éclairé, conformément au principe de transparence consacré par l'article 4 (k) du Décret de 2016. Elle crée aussi un risque d'accumulation : plus les données sont conservées longtemps, plus elles constituent une cible de valeur pour des cyberattaquants. Enfin, l'absence de durée définie rend impossible l'exercice effectif du droit de rectification prévu par l'article 3, alinéa 9, de l'Arrêté de 2018, puisque des données erronées ou obsolètes pourraient être conservées sans limite de temps." },

    { t: 'h2', id: 'souverainete', s: 'Souveraineté technologique et localisation des données' },
    { t: 'p', s: "Certaines plateformes gouvernementales sont hébergées sur des serveurs situés aux États-Unis. Or, depuis 2018, les États-Unis ont adopté le CLOUD Act (Clarifying Lawful Overseas Use of Data Act) : législation permettant aux autorités américaines d'exiger d'un fournisseur de services basé aux États-Unis qu'il donne accès aux données stockées sur ses serveurs, même si ces données concernent des citoyens étrangers et même si les serveurs sont physiquement situés à l'étranger. Corrélativement, les données stockées sur un serveur situé aux États-Unis sont accessibles aux autorités américaines, sans que la nationalité étrangère de la personne concernée constitue, en soi, un obstacle." },
    { t: 'p', s: "Cette situation soulève une question de souveraineté. La législation haïtienne prévoit que les administrés ont droit à « la garantie de sécurité et de confidentialité des données figurant dans les fichiers, systèmes et applications de l'administration publique ». L'hébergement de données gouvernementales sur des serveurs étrangers, sans aucune divulgation aux utilisateurs, pose la question de la compatibilité de cette pratique avec cette garantie légale. Par conséquent, le gouvernement haïtien ne détient pas le contrôle sur les données collectées auprès des utilisateurs sur ses plateformes." },
    { t: 'p', s: "À notre connaissance, aucun accord bilatéral conclu entre Haïti et les États-Unis dans le cadre du CLOUD Act n'a été rendu public, et Haïti ne semble pas avoir adopté, à ce jour, de politique générale de localisation des données. Les États-Unis ont toutefois conclu des accords CLOUD Act avec le Royaume-Uni et l'Australie. Ces accords prévoient des garde-fous : ils sont réservés à des partenaires présentant des garanties suffisantes en matière de protection de la vie privée et des libertés civiles." },
    { t: 'p', s: "D'autres pays, ne pouvant satisfaire aux exigences de libertés civiles requises par ces accords ou ne disposant pas du poids diplomatique nécessaire pour les négocier, ont adopté des exigences de localisation ou des restrictions sur les transferts de données. Ces politiques obligent les opérateurs de services numériques à stocker les données de leurs citoyens sur des serveurs situés physiquement sur le territoire national. La Russie, la Chine, l'Inde, le Vietnam, le Nigeria et le Brésil ont adopté des mesures de localisation des données. Plus près de nous, dans la Caraïbe, ce sont des règles encadrant les transferts transfrontaliers de données qui ont été adoptées, notamment par la Jamaïque, les Bahamas et la Barbade." },

    { t: 'h2', id: 'bilinguisme', s: "L'obligation du bilinguisme" },
    { t: 'p', s: "Le Décret de 2016 prévoit, à son article 49, que « les sites électroniques des entités administratives permettront l'accès à leurs contenus et services en créole et en français ». Or, certaines plateformes gouvernementales ne sont disponibles que dans une seule langue. Cette situation prive une partie significative de la population d'un accès égal aux services publics numériques, en contradiction avec le principe d'égalité des administrés consacré par le même décret." },

    { t: 'h2', id: 'dnssec', s: 'Sécurité des noms de domaine et authentification des sites gouvernementaux' },
    { t: 'p', s: "Lorsqu'un usager saisit l'adresse d'une plateforme dans son navigateur, un mécanisme appelé DNS (Domain Name System) traduit cette adresse en une localisation technique permettant d'atteindre le bon serveur. Ce système est au fondement de la navigation sur internet : il garantit que lorsqu'on tape l'adresse d'un site, il affiche le site authentique et non une copie frauduleuse." },
    { t: 'p', s: "Or, le DNS, tel qu'il a été conçu dans les années 1980, ne dispose d'aucun mécanisme intégré pour vérifier l'authenticité des réponses qu'il fournit. Une technologie appelée DNSSEC (Domain Name System Security Extensions) a été développée pour combler cette lacune. Le DNSSEC ajoute une couche de signature cryptographique aux réponses DNS, permettant au navigateur de l'utilisateur de vérifier que l'adresse obtenue provient bien du détenteur légitime du nom de domaine et qu'elle n'a pas été altérée en cours de route." },
    { t: 'p', s: "Sans DNSSEC, une attaque dite d'empoisonnement de cache DNS est possible. Dans ce scénario, un attaquant exploite le système de résolution de noms pour rediriger les utilisateurs vers un faux site qui imite l'apparence du site officiel (ce type d'attaque s'est produit par le passé sur des sites bancaires). L'utilisateur, croyant se trouver sur la plateforme gouvernementale légitime, saisit ses informations personnelles, qui sont alors captées par l'attaquant. Si le site frauduleux est soigneusement élaboré, l'utilisateur ne dispose d'aucun moyen de détecter l'arnaque." },
    { t: 'p', s: "En effectuant un contrôle en ligne à l'aide de sites publiquement accessibles, nous avons constaté que plusieurs plateformes gouvernementales ne disposent pas du DNSSEC. Cette absence, combinée à un nombre limité de serveurs de noms — parfois seulement deux, hébergés par le même prestataire — réduit la résilience de ces sites face à ce type d'attaque." },
    { t: 'p', s: "En conséquence, un attaquant qui réussit un empoisonnement DNS pourrait créer une copie fidèle d'une plateforme gouvernementale et collecter en temps réel les numéros de passeport, les NINU, les dates de naissance et les numéros de carte de crédit de chaque utilisateur. L'administré n'aurait aucun moyen de savoir que ses données ont été compromises, puisque le faux site pourrait même transmettre les informations au vrai serveur après les avoir copiées, ce qui rendrait l'attaque invisible." },
    { t: 'p', s: "Le Décret du 6 janvier 2016 aborde cette préoccupation à plusieurs niveaux. L'article 17 exige des « systèmes de signature électronique sécurisée attestée par des certificats électroniques qualifiés ou un moyen équivalent ». Si le certificat SSL (le cadenas du navigateur) constitue un premier niveau de protection, il ne protège pas contre l'empoisonnement DNS : un attaquant qui redirige le trafic vers un faux serveur peut aussi y installer un certificat SSL valide. Le DNSSEC et le SSL sont donc complémentaires, et non interchangeables. L'article 4 f) impose par ailleurs « au moins le même niveau de garantie et de sécurité que celui requis pour l'utilisation des moyens non électroniques » : l'authenticité du site doit être vérifiable, ce que le DNSSEC permet de garantir." },

    { t: 'h2', id: 'droits', s: 'Les droits des administrés sur leurs données' },
    { t: 'h3', s: 'Accessibilité et rectification' },
    { t: 'p', s: "Le droit d'accès permet à l'administré de savoir quelles données l'administration détient sur lui ; le droit de rectification lui permet de corriger les erreurs. Le Décret de 2016 (article 9) et l'Arrêté de 2018 (article 3, alinéas 5, 8 et 9) garantissent l'accès limité aux services habilités, l'accessibilité des données à la personne concernée et leur rectification sur demande." },
    { t: 'p', s: "Or, l'analyse de ces plateformes ne nous a pas permis d'identifier un mécanisme d'accès permettant aux utilisateurs de consulter les données les concernant : formulaire de contact, adresse de correspondance ou espace dédié ne sont pas visibles pour exercer un droit de rectification. Quant aux échanges de données entre entités (IHSI, ONI, AGD, DGI…), aucun protocole n'est documenté publiquement. Sans cette documentation, l'obligation légale d'accès limité aux services habilités est invérifiable." },
    { t: 'p', s: "La protection des données ne se résume pas à une action ponctuelle : elle suppose une chaîne de responsabilités continue, de la collecte jusqu'à la suppression, reposant sur trois piliers indissociables — la transparence, la sécurité et l'accessibilité. Chaque plateforme d'e-gouvernance devrait s'inscrire dans un cycle : collecte limitée à la finalité déclarée, traitement sécurisé, partage inter-agences documenté et consenti, conservation limitée dans le temps, suppression ou anonymisation à l'expiration de cette durée." },

    { t: 'h2', id: 'conformite', s: 'Vers une mise en conformité' },
    { t: 'p', s: "Les citoyens disposent de voies de recours. L'Office de la Protection du Citoyen (OPC) veille au respect des droits des administrés en matière d'administration électronique. L'Office de Management et des Ressources Humaines (OMRH), via sa Cellule de Promotion de l'Administration Électronique, accompagne les institutions et formule des recommandations pour sécuriser les services publics numériques." },
    { t: 'p', s: "La digitalisation est une promesse. Pour qu'elle tienne, les plateformes collectant les données à caractère personnel de la population doivent offrir la transparence et la protection que la loi leur impose." },
  ],
  bodyEn: [
    { t: 'p', s: "The digitalization of public services is a positive step forward for Haiti. The Decree of January 6, 2016, recognizing the right of every citizen to interact with the Public Administration through electronic means, lays the foundation for a modern e-government framework that respects citizens' rights. It aims to reduce barriers to accessing public services, simplify administrative procedures, and improve transparency." },
    { t: 'p', s: 'Modernization, however, also brings new challenges. The 2016 Decree establishes standards to ensure the security of electronic systems, the confidentiality of personal data, and the protection of privacy, while encouraging cooperation between administrative entities to ensure the interoperability of systems and applications. It also emphasizes bridging the digital divide and preserving bilingualism (Creole and French) in electronic services.' },
    { t: 'p', s: "It is with this vision that several State agencies have begun modernizing to better serve the population. But trust in these services requires that users' rights be respected. The usefulness of these platforms requires that the transparency and protection standards already provided for by current legislation be effectively implemented from the design stage." },

    { t: 'h2', id: 'data', s: 'Personal data protection: a recognized right' },
    { t: 'p', s: "The Presidential Order of April 30, 2018, on the protection of personal data recognizes citizens' right to the protection of their information. The principles it enshrines are internationally recognized: purpose limitation, proportionality, limited retention, confidentiality, security, right of access, and right of rectification. These principles are aligned with international standards, notably the EU's GDPR and the OECD Privacy Guidelines." },
    { t: 'p', s: "The data collected by government platforms is among the most sensitive in existence: the National Unique Identification Number (NINU), passport numbers, dates of birth, credit card details, personal addresses, and phone numbers — data intrinsically linked to each individual's identity. If accessed by unauthorized persons, they could be used for identity theft, document fraud, or unauthorized surveillance. The 2016 Decree anticipated this risk in Article 4(f) by requiring a level of security at least equal to that provided by non-electronic means." },

    { t: 'h2', id: 'transparency', s: 'Transparency, privacy policy, and data retention' },
    { t: 'p', s: 'Building user trust requires that privacy policies play a central role. They inform citizens of the nature of the data collected, its purpose, its retention period, and the persons authorized to access it. Yet, on several existing government platforms, these policies are absent, not provided for, or inaccessible — sometimes with footer links redirecting to entirely blank pages.' },
    { t: 'p', s: 'The principle of proportionality (data minimization) provided for by the 2018 Order specifies that "only the data strictly necessary for the purpose for which they are requested shall be required from citizens." Without a published privacy policy, citizens cannot verify whether this principle is respected.' },
    { t: 'p', s: 'The absence of a privacy policy also makes it difficult to identify how long submitted data will be retained. The 2018 Order requires (Article 3, paragraph 3) that data be "retained for a period established according to the purpose of the file." Personal data must not be kept indefinitely and must be deleted or anonymized once no longer necessary. A traveler filling an entry/exit form, or an entrepreneur registering a business online, has no way of knowing whether their data will remain for a month, a year, ten years, or indefinitely.' },
    { t: 'p', s: 'This lack of information prevents informed consent (Article 4(k) of the 2016 Decree), creates an accumulation risk (the longer data is retained, the more valuable a target it becomes), and makes the right of rectification (Article 3, paragraph 9, of the 2018 Order) impossible to exercise effectively.' },

    { t: 'h2', id: 'sovereignty', s: 'Technological sovereignty and data localization' },
    { t: 'p', s: 'Certain government platforms are hosted on servers located in the United States. Since 2018, the U.S. CLOUD Act allows U.S. authorities to compel a U.S.-based service provider to grant access to data stored on its servers, even if the data concerns foreign nationals and even if the servers are physically located abroad. Data stored on a U.S. server is accessible to U.S. authorities; the foreign nationality of the data subject is not, in itself, a barrier.' },
    { t: 'p', s: 'This raises a sovereignty question. Haitian legislation guarantees citizens "the security and confidentiality of data contained in the files, systems, and applications of the public administration." Hosting government data on foreign servers, without disclosure, raises the question of compatibility with that guarantee. As a result, the Haitian government does not retain control over the data collected on its platforms.' },
    { t: 'p', s: 'To our knowledge, no bilateral CLOUD Act agreement between Haiti and the United States has been made public, and Haiti has not adopted a general data localization policy. The U.S. has concluded CLOUD Act agreements with the UK and Australia, reserved for partners providing sufficient privacy and civil-liberties guarantees. Other countries — Russia, China, India, Vietnam, Nigeria, Brazil, and, in the Caribbean, Jamaica, the Bahamas and Barbados — have adopted localization requirements or cross-border transfer rules.' },

    { t: 'h2', id: 'bilingual', s: 'The bilingualism requirement' },
    { t: 'p', s: 'The 2016 Decree provides, in Article 49, that "the electronic sites of administrative entities shall provide access to their content and services in Creole and French." Yet some government platforms are available in only one language, depriving a significant portion of the population of equal access — contrary to the principle of equal treatment enshrined in the same decree.' },

    { t: 'h2', id: 'dns', s: 'Domain name security and authentication of government websites' },
    { t: 'p', s: 'When a user enters a platform’s address, the DNS (Domain Name System) translates it into a technical location pointing to the correct server. DNS, as designed in the 1980s, has no built-in mechanism to verify the authenticity of its responses. DNSSEC (DNS Security Extensions) adds cryptographic signatures to DNS responses, letting the browser verify that the address genuinely comes from the legitimate domain holder.' },
    { t: 'p', s: 'Without DNSSEC, DNS cache poisoning attacks are possible: an attacker redirects users to a fake site mimicking the official one, capturing the personal information entered. We found that several government platforms lack DNSSEC, often with only two name servers hosted by the same provider — reducing resilience. An attacker who succeeds could clone a platform and collect, in real time, passport numbers, NINUs, dates of birth and credit card numbers, even relaying them to the real server to stay invisible.' },
    { t: 'p', s: 'The 2016 Decree addresses this at several levels. Article 17 requires secure electronic-signature systems attested by qualified certificates. An SSL certificate (the browser padlock) is a first line of defense but does not protect against DNS poisoning — an attacker can install a valid SSL certificate on a fraudulent domain. DNSSEC and SSL are complementary, not interchangeable. Article 4(f) requires "at least the same level of guarantee and security as that required for the use of non-electronic means": the site’s authenticity must be verifiable, which is precisely what DNSSEC ensures.' },

    { t: 'h2', id: 'rights', s: "Citizens' rights over their data" },
    { t: 'h3', s: 'Accessibility and rectification' },
    { t: 'p', s: "The right of access lets citizens know what data the administration holds about them; the right of rectification lets them correct errors. The 2016 Decree (Article 9) and the 2018 Order (Article 3, paragraphs 5, 8 and 9) guarantee access limited to authorized services, accessibility to the data subject, and rectification on request." },
    { t: 'p', s: "However, our review did not identify any access mechanism — no contact form, correspondence address, or dedicated section — for exercising the right of rectification. As for inter-agency exchanges (IHSI, ONI, AGD, DGI), no data-sharing protocol is publicly documented, making the legal obligation to limit access unverifiable." },
    { t: 'p', s: 'Data protection is not a one-time action: it requires a continuous chain of accountability, from collection to deletion, resting on three inseparable pillars — transparency, security and accessibility. Every e-governance platform should operate within a clear cycle: collection limited to the stated purpose, secure processing, documented and consented inter-agency sharing, time-limited retention, and deletion or anonymization on expiry.' },

    { t: 'h2', id: 'compliance', s: 'Toward compliance' },
    { t: 'p', s: 'Citizens have avenues of recourse. The Office for the Protection of Citizens (OPC) ensures that citizens’ rights are respected in e-government matters. The Office of Management and Human Resources (OMRH), through its Unit for the Promotion of Electronic Administration, supports institutions and formulates recommendations to secure digital public services.' },
    { t: 'p', s: 'Digitalization is a promise. For it to hold, the platforms that collect the population’s personal data must provide the transparency and protection required by law.' },
  ],
  refsEn: [
    'Decree of January 6, 2016 recognizing the right of every citizen to interact with the Public Administration through electronic means.',
    'Order of April 30, 2018 establishing rules on the protection of personal data, Article 3.',
    'Regulation (EU) 2016/679 (GDPR), Article 5; OECD Guidelines on the Protection of Privacy and Transborder Flows of Personal Data (rev. 2013).',
    'Clarifying Lawful Overseas Use of Data Act (CLOUD Act), 18 U.S.C. § 2713; U.S.–UK (2019/2022) and U.S.–Australia (2021) CLOUD Act agreements.',
    'IETF, RFC 4033–4035 (DNS Security Extensions).',
    'Law of May 3, 2012 (Office for the Protection of Citizens); Order of May 25, 2009 (Office of Management and Human Resources).',
  ],
}

export const PUBLICATIONS: PublicationData[] = [EGOUVERNANCE]

export function getPublication(slug: string): PublicationData | undefined {
  return PUBLICATIONS.find((p) => p.slug === slug)
}
