/**
 * Intitulés des 97 chapitres du Système Harmonisé (SH 2022), en français (langue de
 * la nomenclature douanière). Utilisés pour la navigation par chapitre de la section
 * Tarifs douaniers (sommaire + en-têtes). Seuls les chapitres présents en base
 * s'affichent. Le chapitre 77 est réservé (vide) au SH.
 */
export const SH_CHAPTERS: Record<string, string> = {
  '01': 'Animaux vivants',
  '02': 'Viandes et abats comestibles',
  '03': 'Poissons, crustacés et mollusques',
  '04': 'Lait et produits laitiers; œufs; miel',
  '05': "Autres produits d'origine animale",
  '06': 'Plantes vivantes et floriculture',
  '07': 'Légumes, plantes, racines et tubercules alimentaires',
  '08': "Fruits comestibles; écorces d'agrumes ou de melons",
  '09': 'Café, thé, maté et épices',
  '10': 'Céréales',
  '11': 'Produits de la minoterie; malt; amidons; gluten',
  '12': 'Graines et fruits oléagineux; plantes industrielles',
  '13': 'Gommes, résines et autres sucs et extraits végétaux',
  '14': "Matières à tresser; produits d'origine végétale",
  '15': 'Graisses et huiles animales, végétales ou microbiennes',
  '16': 'Préparations de viandes, de poissons ou de crustacés',
  '17': 'Sucres et sucreries',
  '18': 'Cacao et ses préparations',
  '19': 'Préparations à base de céréales, farines, lait; pâtisseries',
  '20': 'Préparations de légumes, de fruits ou de plantes',
  '21': 'Préparations alimentaires diverses',
  '22': 'Boissons, liquides alcooliques et vinaigres',
  '23': 'Résidus des industries alimentaires; aliments pour animaux',
  '24': 'Tabacs et succédanés de tabac',
  '25': 'Sel; soufre; terres et pierres; plâtres, chaux et ciments',
  '26': 'Minerais, scories et cendres',
  '27': 'Combustibles et huiles minéraux; matières bitumineuses; cires',
  '28': 'Produits chimiques inorganiques',
  '29': 'Produits chimiques organiques',
  '30': 'Produits pharmaceutiques',
  '31': 'Engrais',
  '32': 'Extraits tannants/tinctoriaux; pigments; peintures; encres',
  '33': 'Huiles essentielles; parfumerie et produits de toilette',
  '34': 'Savons, agents de surface, cires, pâtes à modeler',
  '35': "Matières albuminoïdes; colles; enzymes",
  '36': 'Poudres et explosifs; pyrotechnie; allumettes',
  '37': 'Produits photographiques ou cinématographiques',
  '38': 'Produits divers des industries chimiques',
  '39': 'Matières plastiques et ouvrages en ces matières',
  '40': 'Caoutchouc et ouvrages en caoutchouc',
  '41': 'Peaux et cuirs',
  '42': 'Ouvrages en cuir; articles de voyage; maroquinerie',
  '43': 'Pelleteries et fourrures; pelleteries factices',
  '44': 'Bois, charbon de bois et ouvrages en bois',
  '45': 'Liège et ouvrages en liège',
  '46': 'Ouvrages de sparterie ou de vannerie',
  '47': 'Pâtes de bois; papier ou carton à recycler',
  '48': 'Papiers et cartons; ouvrages en pâte, papier ou carton',
  '49': "Produits de l'édition et de la presse; manuscrits, plans",
  '50': 'Soie',
  '51': 'Laine, poils fins ou grossiers; fils et tissus de crin',
  '52': 'Coton',
  '53': 'Autres fibres textiles végétales; fils de papier',
  '54': 'Filaments synthétiques ou artificiels',
  '55': 'Fibres synthétiques ou artificielles discontinues',
  '56': 'Ouates, feutres et nontissés; ficelles, cordes',
  '57': 'Tapis et autres revêtements de sol en textiles',
  '58': 'Tissus spéciaux; dentelles; tapisseries; broderies',
  '59': 'Tissus imprégnés ou enduits; articles techniques en textile',
  '60': 'Étoffes de bonneterie',
  '61': 'Vêtements et accessoires, en bonneterie',
  '62': 'Vêtements et accessoires, autres qu’en bonneterie',
  '63': 'Autres articles textiles confectionnés; friperie',
  '64': 'Chaussures, guêtres et articles analogues',
  '65': 'Coiffures et parties de coiffures',
  '66': 'Parapluies, ombrelles, cannes, fouets',
  '67': 'Plumes et duvet apprêtés; fleurs artificielles',
  '68': 'Ouvrages en pierres, plâtre, ciment, amiante',
  '69': 'Produits céramiques',
  '70': 'Verre et ouvrages en verre',
  '71': 'Perles, pierres gemmes, métaux précieux; bijouterie; monnaies',
  '72': 'Fonte, fer et acier',
  '73': 'Ouvrages en fonte, fer ou acier',
  '74': 'Cuivre et ouvrages en cuivre',
  '75': 'Nickel et ouvrages en nickel',
  '76': 'Aluminium et ouvrages en aluminium',
  '78': 'Plomb et ouvrages en plomb',
  '79': 'Zinc et ouvrages en zinc',
  '80': 'Étain et ouvrages en étain',
  '81': 'Autres métaux communs; cermets',
  '82': 'Outils, coutellerie et couverts en métaux communs',
  '83': 'Ouvrages divers en métaux communs',
  '84': 'Réacteurs, chaudières, machines et appareils mécaniques',
  '85': 'Machines, appareils et matériels électriques',
  '86': 'Véhicules et matériel pour voies ferrées; signalisation',
  '87': 'Voitures automobiles, tracteurs, cycles et autres véhicules',
  '88': 'Navigation aérienne ou spatiale',
  '89': 'Navigation maritime ou fluviale',
  '90': 'Instruments d’optique, de mesure, médico-chirurgicaux',
  '91': 'Horlogerie',
  '92': 'Instruments de musique',
  '93': 'Armes, munitions et leurs parties',
  '94': 'Meubles; literie; appareils d’éclairage; constructions préfabriquées',
  '95': 'Jouets, jeux, articles pour divertissements ou sports',
  '96': 'Ouvrages divers',
  '97': "Objets d'art, de collection ou d'antiquité",
}

/** Intitulé d'un chapitre (code « 01 » → titre), ou le code si inconnu. */
export function chapterLabel(code: string): string {
  return SH_CHAPTERS[code] ?? `Chapitre ${code}`
}
