import Link from 'next/link'
import { MapPin, ShieldCheck, ChevronRight } from 'lucide-react'
import { LocaleSwitcher } from '@/components/LocaleSwitcher'
import { CookieBanner } from '@/components/CookieBanner'
import { HeroJudicialMapArt } from '@/components/home/HeroJudicialMapArt'
import type { SaisieHeros } from '@/components/delais/noyau-calculateur'
import type { Dictionary } from '@/lib/i18n/dictionaries'
import type { Locale } from '@/lib/types'
import { BRAND } from '@/lib/brand'
import { JudicialSearch } from '@/components/jurisdictions/JudicialSearch'
import { AgoraNextHoliday } from './AgoraNextHoliday'
import './agora-portal.css'

export type AgoraLandingProps = { locale: Locale; t: Dictionary; delais?: SaisieHeros | null }

/** Public entry point; document access requires authentication; the public portal presents the judicial map. */
export function AgoraLanding({ locale, t }: AgoraLandingProps) {
  const tr = (fr: string, en: string, ht: string) => locale === 'en' ? en : locale === 'ht' ? ht : fr
  return <div className="agora-portal">
    <a className="ag-skip" href="#agora-main">{tr('Aller au contenu', 'Skip to content', 'Ale nan kontni an')}</a>

    <header className="ag-header"><div className="ag-container ag-header-inner">
      <Link href={`/${locale}`} aria-label="Agora — accueil" className="ag-brand"><img src="/brand/agora/logo.png" alt="agora.ht" width="190" height="63" /></Link>
      <nav className="ag-nav" aria-label={tr('Navigation principale', 'Main navigation', 'Navigasyon prensipal')}><a href="#carte-judiciaire" aria-current="page">{tr('Carte judiciaire', 'Judicial map', 'Kat jidisyè')}</a><a href="#presentation">{tr('Présentation', 'About the map', 'Prezantasyon')}</a><Link href={`/${locale}/fetes-legales`}>{tr("Fêtes légales", "Public holidays", "Jou ferye")}</Link></nav>
      <div className="ag-header-actions"><div className="ag-language"><LocaleSwitcher current={locale} /></div><Link href={`/${locale}/login`} className="ag-button ag-login">{tr('Accès sécurisé', 'Secure access', 'Aksè sekirize')}</Link></div>
    </div></header>

    <main id="agora-main">
      <section className="ag-hero ag-container" id="carte-judiciaire"><div className="ag-hero-grid">
        <div className="ag-search-workspace"><p className="ag-eyebrow">{tr('La carte judiciaire haïtienne', 'The Haitian judicial map', 'Kat jidisyè Ayiti a')}</p><h1>{tr('La justice en Haïti,', 'Justice in Haiti,', 'Jistis an Ayiti,')}<br /><em>{tr('sur une même carte.', 'on one map.', 'sou yon sèl kat.')}</em></h1><p className="ag-hero-description">{tr('Découvrez l’organisation judiciaire du territoire. Repérez les juridictions par ville, commune ou code postal et comprenez leur répartition en Haïti.', 'Discover the judicial organization of the territory. Locate courts by town, commune or postal code and understand their distribution across Haiti.', 'Dekouvri òganizasyon jidisyè teritwa a. Idantifye jiridiksyon yo pa vil, komin oswa kòd postal epi konprann repartisyon yo an Ayiti.')}</p><div className="ag-commune-picker"><JudicialSearch locale={locale} t={t} layersQs="" /></div><Link href={`/${locale}/juridictions`} className="ag-button ag-map-primary"><MapPin size={18} aria-hidden="true" />{tr('Explorer la carte judiciaire', 'Explore the judicial map', 'Eksplore kat jidisyè a')}</Link>
        </div>
        <aside className="ag-judicial-preview"><div className="ag-judicial-heading"><span className="ag-eyebrow">{tr('Le droit, près de vous', 'The law, close to you', 'Dwa a, toupre ou')}</span><MapPin size={20} aria-hidden="true" /></div><h2>{tr('À chaque commune,', 'For every commune,', 'Pou chak komin,')}<br />{tr('ses juridictions.', 'its jurisdictions.', 'jiridiksyon li yo.')}</h2><Link className="ag-map-art ag-map-clickable" href={`/${locale}/juridictions`} aria-label={tr("Explorer la carte judiciaire", "Explore the judicial map", "Eksplore kat jidisyè a")}><HeroJudicialMapArt /></Link><div className="ag-map-place"><span><MapPin size={15} aria-hidden="true" />Port-au-Prince</span><span>HT6110</span></div><Link className="ag-map-link" href={`/${locale}/juridictions`}>{tr('Ouvrir la carte', 'Open the map', 'Louvri kat la')}<ChevronRight size={18} aria-hidden="true" /></Link></aside>
      </div></section>
      <section id="presentation" className="ag-mission"><div className="ag-container"><div className="ag-section-heading"><div><p className="ag-eyebrow">{tr('Comprendre la carte judiciaire', 'Understand the judicial map', 'Konprann kat jidisyè a')}</p><h2>{tr('Un repère pour chaque commune.', 'A reference for every commune.', 'Yon referans pou chak komin.')}</h2></div></div><div className="ag-map-features">
        {[[tr('Choisissez votre commune','Choose your commune','Chwazi komin ou'),tr('Saisissez une ville, une commune ou un code postal.','Enter a town, commune or postal code.','Antre yon vil, yon komin oswa yon kòd postal.')],[tr('Découvrez ses juridictions','Discover its courts','Dekouvri jiridiksyon li yo'),tr('Repérez les tribunaux et leur ressort sur la carte.','Locate courts and their jurisdiction on the map.','Idantifye tribinal yo ak teritwa yo sou kat la.')],[tr('Consultez leur fiche','View their details','Gade fich yo'),tr('Retrouvez les informations disponibles, leurs sources et leur date de vérification.','Find available information, sources and verification dates.','Jwenn enfòmasyon ki disponib, sous yo ak dat verifikasyon yo.')]].map(([title,description],i)=><article key={i}><span className="ag-step-number">0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}
      </div></div></section>
      <AgoraNextHoliday locale={locale} />
      <section className="ag-disclaimer ag-container"><ShieldCheck size={23} aria-hidden="true" /><div><h2>{tr('L’information, avec ses sources.', 'Information, with its sources.', 'Enfòmasyon, ak sous li yo.')}</h2><p>{tr('La carte judiciaire constitue un outil d’information et de repérage. Elle ne remplace pas les sources officielles ni la vérification auprès des juridictions concernées. Son utilisation ne constitue pas un conseil juridique et ne crée aucune relation avocat-client.', 'The judicial map is an information and orientation tool. It does not replace official sources or verification with the relevant courts. Its use does not constitute legal advice and creates no attorney-client relationship.', 'Kat jidisyè a se yon zouti enfòmasyon ak oryantasyon. Li pa ranplase sous ofisyèl yo ni verifikasyon bò kote jiridiksyon konsène yo. Itilizasyon li pa reprezante konsèy jiridik epi li pa kreye relasyon avoka-kliyan.')}</p></div></section>
    </main>
    <footer className="ag-footer"><div className="ag-container"><div className="ag-footer-grid"><div className="ag-footer-brand"><img src="/brand/agora/logo-white.png" alt="agora.ht" width="190" height="63" /><p>{tr('La carte judiciaire haïtienne.', 'The Haitian judicial map.', 'Kat jidisyè Ayiti a.')}</p></div><nav aria-label={tr('Explorer', 'Explore', 'Eksplore')}><h3>{tr('Explorer', 'Explore', 'Eksplore')}</h3><Link href={`/${locale}/login`}>{tr('Accès sécurisé', 'Secure access', 'Aksè sekirize')}</Link><Link href={`/${locale}/juridictions`}>{tr('Carte judiciaire','Judicial map','Kat jidisyè')}</Link><a href="#presentation">{tr('Présentation','About the map','Prezantasyon')}</a></nav><nav aria-label={tr('Informations légales','Legal information','Enfòmasyon legal')}><h3>{tr('Informations légales','Legal information','Enfòmasyon legal')}</h3><Link href={`/${locale}/cgu`}>{t.legal.cgu}</Link><Link href={`/${locale}/confidentialite`}>{t.legal.confidentialite}</Link><Link href={`/${locale}/mentions-legales`}>{t.legal.mentions}</Link></nav><nav aria-label="Contact"><h3>Contact</h3><a href="mailto:legal@agora.ht">legal@agora.ht</a><a href="mailto:erreur@agora.ht">{tr('Signaler une erreur','Report an error','Siyale yon erè')}</a></nav></div><div className="ag-footer-bottom"><span>© {new Date().getFullYear()} Agora · {tr('Reproductions documentaires','Documentary reproductions','Repwodiksyon dokiman')}</span><span>{tr('Éditeur : Agora · Pétion-Ville, Haïti','Publisher: Agora · Pétion-Ville, Haiti','Editè : Agora · Petyonvil, Ayiti')}</span><span className="ag-transition">{BRAND.transition[locale]}</span></div></div></footer>
    <div className="ag-consent"><CookieBanner text={tr('Agora utilise des cookies nécessaires à la session et à la langue. Les cookies d’analyse sont soumis à votre accord.', 'Agora uses cookies required for sessions and language. Analytics cookies require your consent.', 'Agora itilize cookies ki nesesè pou sesyon ak lang. Cookies analiz bezwen akò ou.')} accept={tr('Tout accepter','Accept all','Aksepte tout')} reject={tr('Refuser les non essentiels','Reject non-essential','Refize sa ki pa esansyèl')} manage={tr('Gérer','Manage','Jere')} manageHref={`/${locale}/confidentialite#s9`} /></div>
  </div>
}
